# Bundle macOS dylib dependencies next to the Slidescape executable and rewrite
# install names so the app can run on machines without Homebrew/MacPorts.

if(NOT DEFINED BUNDLE_BINARY_DIR)
	message(FATAL_ERROR "BUNDLE_BINARY_DIR is required")
endif()

if(NOT DEFINED ARCHITECTURE)
	message(FATAL_ERROR "ARCHITECTURE is required")
endif()

set(BUNDLE_DYLIB_DIR "${BUNDLE_BINARY_DIR}/${ARCHITECTURE}")
set(BUNDLE_DYLIB_INSTALL_NAME_PREFIX "@executable_path/${ARCHITECTURE}")
file(MAKE_DIRECTORY "${BUNDLE_DYLIB_DIR}")

set_property(GLOBAL PROPERTY BUNDLED_SOURCE_PATHS "")

function(is_macos_system_library DYLIB_PATH RESULT_VAR)
	if("${DYLIB_PATH}" MATCHES "^/usr/lib/" OR
			"${DYLIB_PATH}" MATCHES "^/System/Library/" OR
			"${DYLIB_PATH}" MATCHES "^/Library/Apple/")
		set(${RESULT_VAR} TRUE PARENT_SCOPE)
	else()
		set(${RESULT_VAR} FALSE PARENT_SCOPE)
	endif()
endfunction()

function(resolve_macos_dylib_path DYLIB_PATH LOADER_PATH RESULT_VAR)
	set(RESULT "")
	if(EXISTS "${DYLIB_PATH}")
		set(RESULT "${DYLIB_PATH}")
	elseif("${DYLIB_PATH}" MATCHES "^@loader_path/")
		string(REGEX REPLACE "^@loader_path/" "" RELATIVE_PATH "${DYLIB_PATH}")
		set(CANDIDATE "${LOADER_PATH}/${RELATIVE_PATH}")
		if(EXISTS "${CANDIDATE}")
			set(RESULT "${CANDIDATE}")
		endif()
	elseif("${DYLIB_PATH}" MATCHES "^@executable_path/")
		string(REGEX REPLACE "^@executable_path/" "" RELATIVE_PATH "${DYLIB_PATH}")
		set(CANDIDATE "${BUNDLE_BINARY_DIR}/${RELATIVE_PATH}")
		if(EXISTS "${CANDIDATE}")
			set(RESULT "${CANDIDATE}")
		endif()
	endif()
	set(${RESULT_VAR} "${RESULT}" PARENT_SCOPE)
endfunction()

function(bundle_macos_dylib SOURCE_PATH DEST_BASENAME)
	resolve_macos_dylib_path("${SOURCE_PATH}" "" RESOLVED_SOURCE_PATH)
	if(NOT RESOLVED_SOURCE_PATH)
		message(WARNING "Skipping unresolved dylib: ${SOURCE_PATH}")
	else()
		get_filename_component(SOURCE_REALPATH "${RESOLVED_SOURCE_PATH}" REALPATH)
		get_property(BUNDLED_SOURCE_PATHS GLOBAL PROPERTY BUNDLED_SOURCE_PATHS)
		list(FIND BUNDLED_SOURCE_PATHS "${SOURCE_REALPATH}" ALREADY_BUNDLED)
		set(DEST_PATH "${BUNDLE_DYLIB_DIR}/${DEST_BASENAME}")
		set(BUNDLED_INSTALL_NAME "${BUNDLE_DYLIB_INSTALL_NAME_PREFIX}/${DEST_BASENAME}")
		if(ALREADY_BUNDLED EQUAL -1)
			list(APPEND BUNDLED_SOURCE_PATHS "${SOURCE_REALPATH}")
			set_property(GLOBAL PROPERTY BUNDLED_SOURCE_PATHS "${BUNDLED_SOURCE_PATHS}")
			get_filename_component(SOURCE_DIR "${SOURCE_REALPATH}" DIRECTORY)

			message(STATUS "Bundling ${SOURCE_REALPATH} -> ${DEST_PATH}")
			execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${SOURCE_REALPATH}" "${DEST_PATH}"
					RESULT_VARIABLE COPY_RESULT)
			if(NOT COPY_RESULT EQUAL 0)
				message(FATAL_ERROR "Failed to copy ${SOURCE_REALPATH} to ${DEST_PATH}")
			endif()

			execute_process(COMMAND chmod u+w "${DEST_PATH}")
			execute_process(COMMAND install_name_tool -id "${BUNDLED_INSTALL_NAME}" "${DEST_PATH}"
					RESULT_VARIABLE SET_ID_RESULT)
			if(NOT SET_ID_RESULT EQUAL 0)
				message(FATAL_ERROR "Failed to set install name for ${DEST_PATH}")
			endif()

			execute_process(COMMAND otool -L "${SOURCE_REALPATH}"
					OUTPUT_VARIABLE OTOOL_OUTPUT
					RESULT_VARIABLE OTOOL_RESULT)
			if(NOT OTOOL_RESULT EQUAL 0)
				message(FATAL_ERROR "otool failed for ${SOURCE_REALPATH}")
			endif()

			string(REPLACE "\n" ";" OTOOL_LINES "${OTOOL_OUTPUT}")
			set(IS_FIRST_OTOOLED_DYLIB TRUE)
			foreach(OTOOL_LINE ${OTOOL_LINES})
				if("${OTOOL_LINE}" MATCHES "\\(architecture [^)]+\\):")
					set(IS_FIRST_OTOOLED_DYLIB TRUE)
				endif()
				string(REGEX MATCH "^[\t ]+([^\t ]+)" DEP_MATCH "${OTOOL_LINE}")
				if(DEP_MATCH)
					set(DEPENDENCY_PATH "${CMAKE_MATCH_1}")
					if(IS_FIRST_OTOOLED_DYLIB)
						set(IS_FIRST_OTOOLED_DYLIB FALSE)
					else()
						is_macos_system_library("${DEPENDENCY_PATH}" IS_SYSTEM_LIBRARY)
						if(NOT IS_SYSTEM_LIBRARY)
							resolve_macos_dylib_path("${DEPENDENCY_PATH}" "${SOURCE_DIR}" RESOLVED_DEPENDENCY_PATH)
							if(RESOLVED_DEPENDENCY_PATH)
									get_filename_component(DEPENDENCY_BASENAME "${DEPENDENCY_PATH}" NAME)
									bundle_macos_dylib("${RESOLVED_DEPENDENCY_PATH}" "${DEPENDENCY_BASENAME}")
									execute_process(COMMAND install_name_tool -change "${DEPENDENCY_PATH}"
											"${BUNDLE_DYLIB_INSTALL_NAME_PREFIX}/${DEPENDENCY_BASENAME}" "${DEST_PATH}"
											RESULT_VARIABLE CHANGE_RESULT)
								if(NOT CHANGE_RESULT EQUAL 0)
									message(FATAL_ERROR "Failed to rewrite ${DEPENDENCY_PATH} in ${DEST_PATH}")
								endif()
							else()
								message(WARNING "Could not resolve dependency ${DEPENDENCY_PATH} referenced by ${SOURCE_REALPATH}")
							endif()
						endif()
					endif()
				endif()
			endforeach()
		endif()
	endif()
endfunction()

if(DEFINED SDL2_DYLIB AND EXISTS "${SDL2_DYLIB}")
	if(NOT DEFINED SDL2_LINK_NAME OR "${SDL2_LINK_NAME}" STREQUAL "")
		execute_process(COMMAND otool -L "${BUNDLE_BINARY_DIR}/Slidescape"
				OUTPUT_VARIABLE SLIDESCAPE_OTOOL_OUTPUT
				RESULT_VARIABLE SLIDESCAPE_OTOOL_RESULT)
		if(NOT SLIDESCAPE_OTOOL_RESULT EQUAL 0)
			message(FATAL_ERROR "otool failed for ${BUNDLE_BINARY_DIR}/Slidescape")
		endif()
		string(REPLACE "\n" ";" SLIDESCAPE_OTOOL_LINES "${SLIDESCAPE_OTOOL_OUTPUT}")
		foreach(OTOOL_LINE ${SLIDESCAPE_OTOOL_LINES})
			string(REGEX MATCH "^[\t ]+([^\t ]*SDL2[^\t ]*)" SDL2_MATCH "${OTOOL_LINE}")
			if(SDL2_MATCH)
				set(SDL2_LINK_NAME "${CMAKE_MATCH_1}")
			endif()
		endforeach()
	endif()
	if(NOT DEFINED SDL2_LINK_NAME OR "${SDL2_LINK_NAME}" STREQUAL "")
		message(FATAL_ERROR "Could not determine SDL2 install name used by Slidescape")
	endif()
	bundle_macos_dylib("${SDL2_DYLIB}" "libSDL2.dylib")
	execute_process(COMMAND install_name_tool -change "${SDL2_LINK_NAME}"
			"@executable_path/${ARCHITECTURE}/libSDL2.dylib" "${BUNDLE_BINARY_DIR}/Slidescape"
			RESULT_VARIABLE SDL2_CHANGE_RESULT)
	if(NOT SDL2_CHANGE_RESULT EQUAL 0)
		message(FATAL_ERROR "Failed to rewrite SDL2 install name in Slidescape")
	endif()
endif()

if(DEFINED OPENSLIDE_DYLIB AND EXISTS "${OPENSLIDE_DYLIB}")
	set(BUNDLE_DYLIB_DIR "${BUNDLE_BINARY_DIR}")
	set(BUNDLE_DYLIB_INSTALL_NAME_PREFIX "@executable_path")
	bundle_macos_dylib("${OPENSLIDE_DYLIB}" "libopenslide.dylib")
endif()
